global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: site-monitoring
    metrics_path: /probe
    params:
      module: [http_2xx]  # Vérifie que le site répond avec un code 2xx
    static_configs:
      - targets:
        # TODO: Besoin de changer les noms des conteneurs foo_bar -> foo-bar
        - http://localhost:8020/
        - http://localhost:8020/api/health/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
