groups:
  - name: site-monitoring
    rules:
      - alert: SiteDown
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service inaccessible: {{ $labels.instance }}"
          description: "Le service {{ $labels.instance }} est inaccessible depuis 1 minute."
